<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-19T16:24:51 IST" name="Default suite" finished-at="2025-10-19T16:25:47 IST" duration-ms="55265">
    <groups>
    </groups>
    <test started-at="2025-10-19T16:24:51 IST" name="Default test" finished-at="2025-10-19T16:25:47 IST" duration-ms="55265">
      <class name="StockExchange.BaseStock">
        <test-method is-config="true" signature="initialization()[pri:0, instance:StockExchange.BaseStock@6150c3ec]" started-at="2025-10-19T16:24:51 IST" name="initialization" finished-at="2025-10-19T16:25:14 IST" duration-ms="22426" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method signature="openingAboutNSE()[pri:1, instance:StockExchange.BaseStock@6150c3ec]" started-at="2025-10-19T16:25:14 IST" name="openingAboutNSE" finished-at="2025-10-19T16:25:28 IST" duration-ms="14111" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openingAboutNSE -->
        <test-method signature="openingList()[pri:2, instance:StockExchange.BaseStock@6150c3ec]" started-at="2025-10-19T16:25:28 IST" name="openingList" finished-at="2025-10-19T16:25:39 IST" duration-ms="10556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openingList -->
        <test-method signature="openingInvest()[pri:3, instance:StockExchange.BaseStock@6150c3ec]" started-at="2025-10-19T16:25:39 IST" name="openingInvest" finished-at="2025-10-19T16:25:43 IST" duration-ms="4113" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [NSE - National Stock Exchange of India Ltd: Live Share/Stock Market News &amp; Updates, Quotes- Nseindia.com] but found [Overview],
expected [NSE - National Stock Exchange of India Ltd: Live Share/Stock Market News &amp; Updates, Quotes- Nseindia.com] but found [Stamp Duty, Compliance for Trading Members - NSE India]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [NSE - National Stock Exchange of India Ltd: Live Share/Stock Market News &amp; Updates, Quotes- Nseindia.com] but found [Overview],
expected [NSE - National Stock Exchange of India Ltd: Live Share/Stock Market News &amp; Updates, Quotes- Nseindia.com] but found [Stamp Duty, Compliance for Trading Members - NSE India]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at StockExchange.HomePage.openingInvest(HomePage.java:96)
at StockExchange.BaseStock.openingInvest(BaseStock.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openingInvest -->
        <test-method signature="testFailExample()[pri:4, instance:StockExchange.BaseStock@6150c3ec]" started-at="2025-10-19T16:25:43 IST" name="testFailExample" finished-at="2025-10-19T16:25:46 IST" duration-ms="3255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailExample -->
        <test-method is-config="true" signature="close()[pri:0, instance:StockExchange.BaseStock@6150c3ec]" started-at="2025-10-19T16:25:46 IST" name="close" finished-at="2025-10-19T16:25:47 IST" duration-ms="635" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- StockExchange.BaseStock -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
